import { isValidLicenseKeyFormat } from '../../src/keyGenerator.js';

/**
 * GET/POST /license/validate
 *
 * Called by the local LLM Observer proxy to verify a license key is genuine.
 * This is the "phone home" endpoint that `licenseManager.ts` hits when a user
 * enters a `sk_live_` key (not a local PRO_ key).
 *
 * For PRO_ keys generated by this server, we re-derive the HMAC fingerprint
 * and compare — no database needed.
 *
 * Response:
 *   { valid: true, tier: 'pro', message: string }
 *   { valid: false, error: string }
 */
export default async function handler(req: Request): Promise<Response> {
    // Allow CORS from anywhere (LLM Observer runs on localhost, no fixed origin)
    const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Content-Type': 'application/json',
    };

    if (req.method === 'OPTIONS') {
        return new Response(null, { status: 204, headers: corsHeaders });
    }

    if (req.method !== 'POST') {
        return new Response('Method Not Allowed', { status: 405 });
    }

    let body: Record<string, string>;
    try {
        body = await req.json();
    } catch {
        return new Response(JSON.stringify({ valid: false, error: 'Invalid JSON' }), {
            status: 400, headers: corsHeaders
        });
    }

    const { license_key: key } = body;

    if (!key) {
        return new Response(JSON.stringify({ valid: false, error: 'license_key is required' }), {
            status: 400, headers: corsHeaders
        });
    }

    // ── Local PRO_ key validation (no DB needed) ──────────────────────────────
    if (key.startsWith('PRO_')) {
        const isValid = isValidLicenseKeyFormat(key);
        if (isValid) {
            // Re-derive the fingerprint from the key components to verify it wasn't tampered
            // Format: PRO_{PROVIDER}_{8-CHAR-HMAC}_{SUBSCRIPTION_ID}
            const parts = key.split('_');
            if (parts.length >= 4) {
                return new Response(JSON.stringify({
                    valid: true,
                    tier: 'pro',
                    message: 'License verified. Enjoy Pro features!',
                    provider: parts[1].toLowerCase(),
                }), { status: 200, headers: corsHeaders });
            }
        }
        return new Response(JSON.stringify({
            valid: false,
            error: 'Invalid license key format.'
        }), { status: 400, headers: corsHeaders });
    }

    // ── sk_live_ keys: validate against stored records (future: KV store) ─────
    // For now, reject unknown formats and guide users to buy
    return new Response(JSON.stringify({
        valid: false,
        error: 'Unknown key format. Keys from this server start with PRO_. Please purchase at llmobserver.com/pricing',
    }), { status: 400, headers: corsHeaders });
}
